import { DECK_LANDING_SECTION_ORDER, type DeckLandingSectionId } from './deck-landing-section-order';

export const DECK_SECTION_ORDER = DECK_LANDING_SECTION_ORDER;

/** Variantes React autorisées par identifiant de section (source unique pour API éditeur + modular landing). */
export const DECK_VARIANT_CHOICES: Record<DeckLandingSectionId, readonly string[]> = {
  hero: [
    'HeroSplitImageRight',
    'HeroFullBleed',
    'HeroGlowVault',
    'HeroParallaxLayers',
    'HeroCardsFan',
    'HeroCardsStrip',
    'HeroCardsMosaic',
  ],
  deck_identity: [
    'IdentityPanel',
    'IdentityMinimal',
    'IdentityPanelFramed',
    'IdentityPanelStory',
    'IdentityMinimalCalm',
    'IdentityMinimalEditorial',
  ],
  for_who: [
    'ForWhoTwoColumns',
    'ForWhoPillars',
    'ForWhoTwoColumnsGuide',
    'ForWhoTwoColumnsStory',
    'ForWhoPillarsInsight',
    'ForWhoPillarsCompass',
  ],
  outcomes: [
    'OutcomesBentoGrid',
    'OutcomesSignalStrip',
    'OutcomesBentoGridAura',
    'OutcomesBentoGridFocus',
    'OutcomesSignalStripFlow',
    'OutcomesSignalStripCalm',
  ],
  how_to_use: [
    'HowToNumbered',
    'HowToTimeline',
    'HowToNumberedQuickstart',
    'HowToNumberedRitual',
    'HowToTimelineFlow',
    'HowToTimelineCompass',
  ],
  in_the_box: [
    'IncludedChecklist',
    'IncludedHighlightGrid',
    'IncludedChecklistEssentials',
    'IncludedChecklistPremium',
    'IncludedHighlightGridTiles',
    'IncludedHighlightGridShowcase',
  ],
  card_gallery: [
    'CardGalleryGrid',
    'CardGalleryScroll',
    'CardGalleryGridCurated',
    'CardGalleryGridDense',
    'CardGalleryScrollSnap',
    'CardGalleryScrollMomentum',
  ],
  photo_gallery: [
    'PhotoSpotlightGrid',
    'PhotoFilmstripRow',
    'PhotoCinematicCollage',
    'PhotoMasonryCascade',
    'PhotoSpotlightGridEditorial',
    'PhotoFilmstripRowStory',
    'PhotoCinematicCollageNarrative',
    'PhotoMasonryCascadeAmbient',
  ],
  faq: [
    'FaqAccordion',
    'FaqTwoColumn',
    'FaqAccordionCalm',
    'FaqAccordionDeep',
    'FaqTwoColumnGuide',
    'FaqTwoColumnBalanced',
  ],
  creator: [
    'CreatorSpotlight',
    'CreatorQuoteBand',
    'CreatorSpotlightNarrative',
    'CreatorSpotlightPortrait',
    'CreatorQuoteBandManifesto',
    'CreatorQuoteBandSignature',
  ],
  testimonials: [
    'TestimonialStrip',
    'TestimonialSpotlight',
    'TestimonialStripVoices',
    'TestimonialStripMomentum',
    'TestimonialSpotlightHuman',
    'TestimonialSpotlightImmersive',
  ],
  newsletter_cta: [
    'NewsletterInline',
    'NewsletterSplit',
    'NewsletterInlineCalm',
    'NewsletterInlinePulse',
    'NewsletterSplitEditorial',
    'NewsletterSplitMinimal',
  ],
  related_decks: [
    'RelatedDecksGrid',
    'RelatedDecksInline',
    'RelatedDecksGridShowcase',
    'RelatedDecksGridCurated',
    'RelatedDecksInlineJourney',
    'RelatedDecksInlineSimple',
  ],
  cta_band: [
    'CtaMarqueeRibbon',
    'CtaSplitAction',
    'CtaMarqueeRibbonGlow',
    'CtaMarqueeRibbonCalm',
    'CtaSplitActionFocus',
    'CtaSplitActionDual',
  ],
};
