/** Variante React → chemin relatif sous `apps/web/src/sections/`. */
export const VARIANT_TO_SPEC_REL: Record<string, string> = {
  HeroCardsFan: 'hero/variants/HeroCardsFan.spec.md',
  HeroCardsMosaic: 'hero/variants/HeroCardsMosaic.spec.md',
  HeroCardsStrip: 'hero/variants/HeroCardsStrip.spec.md',
  HeroSplitImageRight: 'hero/variants/HeroSplitImageRight.spec.md',
  HeroFullBleed: 'hero/variants/HeroFullBleed.spec.md',
  HeroGlowVault: 'hero/variants/HeroGlowVault.spec.md',
  HeroParallaxLayers: 'hero/variants/HeroParallaxLayers.spec.md',
  IdentityPanel: 'deck_identity/variants/IdentityPanel.spec.md',
  IdentityMinimal: 'deck_identity/variants/IdentityMinimal.spec.md',
  ForWhoTwoColumns: 'for_who/variants/ForWhoTwoColumns.spec.md',
  ForWhoPillars: 'for_who/variants/ForWhoPillars.spec.md',
  OutcomesBentoGrid: 'outcomes/variants/OutcomesBentoGrid.spec.md',
  OutcomesSignalStrip: 'outcomes/variants/OutcomesSignalStrip.spec.md',
  HowToNumbered: 'how_to_use/variants/HowToNumbered.spec.md',
  HowToTimeline: 'how_to_use/variants/HowToTimeline.spec.md',
  CtaMarqueeRibbon: 'cta_band/variants/CtaMarqueeRibbon.spec.md',
  CtaSplitAction: 'cta_band/variants/CtaSplitAction.spec.md',
  IncludedChecklist: 'in_the_box/variants/IncludedChecklist.spec.md',
  IncludedHighlightGrid: 'in_the_box/variants/IncludedHighlightGrid.spec.md',
  CardGalleryGrid: 'card_gallery/variants/CardGalleryGrid.spec.md',
  CardGalleryScroll: 'card_gallery/variants/CardGalleryScroll.spec.md',
  PhotoSpotlightGrid: 'photo_gallery/variants/PhotoSpotlightGrid.spec.md',
  PhotoFilmstripRow: 'photo_gallery/variants/PhotoFilmstripRow.spec.md',
  FaqAccordion: 'faq/variants/FaqAccordion.spec.md',
  FaqTwoColumn: 'faq/variants/FaqTwoColumn.spec.md',
  CreatorSpotlight: 'creator/variants/CreatorSpotlight.spec.md',
  CreatorQuoteBand: 'creator/variants/CreatorQuoteBand.spec.md',
  RelatedDecksGrid: 'related_decks/variants/RelatedDecksGrid.spec.md',
  RelatedDecksInline: 'related_decks/variants/RelatedDecksInline.spec.md',
};
